# Form implementation generated from reading ui file 'c:\Users\Frizx\Desktop\Kinlane-main\client\app\ui/forms\add_new_playlist_dialog_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(337, 372)
        Form.setWindowTitle("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.title = QtWidgets.QLineEdit(parent=Form)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_name = QtWidgets.QLabel(parent=Form)
        self.file_name.setObjectName("file_name")
        self.horizontalLayout.addWidget(self.file_name)
        self.select_file = QtWidgets.QPushButton(parent=Form)
        self.select_file.setObjectName("select_file")
        self.horizontalLayout.addWidget(self.select_file)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.description = QtWidgets.QTextEdit(parent=Form)
        self.description.setObjectName("description")
        self.verticalLayout_2.addWidget(self.description)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.create = QtWidgets.QPushButton(parent=Form)
        self.create.setObjectName("create")
        self.horizontalLayout_2.addWidget(self.create)
        self.cancel = QtWidgets.QPushButton(parent=Form)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.error_label = QtWidgets.QLabel(parent=Form)
        self.error_label.setObjectName("error_label")
        self.verticalLayout_3.addWidget(self.error_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("Form", "Назва"))
        self.file_name.setText(_translate("Form", "Виберіть лого"))
        self.select_file.setText(_translate("Form", "Вибрати файл"))
        self.label_3.setText(_translate("Form", "Опис"))
        self.create.setText(_translate("Form", "Створити"))
        self.cancel.setText(_translate("Form", "Скасувати"))
        self.error_label.setText(_translate("Form", "TextLabel"))
