# Form implementation generated from reading ui file 'c:\Users\Frizx\Desktop\Kinlane-main\client\app\ui/forms\check_box_playlists_component.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(168, 38)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.playlists = QtWidgets.QCheckBox(parent=Form)
        self.playlists.setCheckable(True)
        self.playlists.setChecked(False)
        self.playlists.setTristate(False)
        self.playlists.setObjectName("playlists")
        self.verticalLayout.addWidget(self.playlists)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.playlists.setText(_translate("Form", "playlists"))
