# Form implementation generated from reading ui file 'c:\Users\Frizx\Desktop\Kinlane-main\client\app\ui/forms\vertical_mediaItem_widget.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(168, 146)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.preview = QtWidgets.QLabel(parent=Form)
        self.preview.setScaledContents(True)
        self.preview.setObjectName("preview")
        self.verticalLayout.addWidget(self.preview)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dop = QtWidgets.QLabel(parent=Form)
        self.dop.setObjectName("dop")
        self.verticalLayout_2.addWidget(self.dop)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.title = QtWidgets.QLabel(parent=Form)
        self.title.setObjectName("title")
        self.verticalLayout_3.addWidget(self.title)
        self.description = QtWidgets.QTextBrowser(parent=Form)
        self.description.setObjectName("description")
        self.verticalLayout_3.addWidget(self.description)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.preview.setText(_translate("Form", "TextLabel"))
        self.dop.setText(_translate("Form", "TextLabel"))
        self.title.setText(_translate("Form", "TextLabel"))
